### ISSUE TITLE
missing styling

### ISSUE THREAD

**Issue by Jimmi08** [CaMer0n/bullets#1]
Shortcode BULLET_ICON_STYLE  wasn't used in template, so there was no styling

With this commit it looks like this:
https://github.com/Jimmi08/bullets/commit/1a2117c041f2b4970d546587263a60d5a5354283

But css should be part of theme, not plugin

![image](https://user-images.githubusercontent.com/5429548/47257341-a4c9d200-d48c-11e8-9564-2fb982ebf298.png)

**Comment by CaMer0n** [comment]
Closing. Bootstrap styles are used by default.
